version: "3.8"

services:
  web:
    build: .
    container_name: django-backend
    restart: always
    depends_on:
      - db
      - redis
    env_file: .env
    ports:
      - "8001:8001"
    volumes:
      - .:/backend_app

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: eduplat_database
      POSTGRES_USER: eduplat_user
      POSTGRES_PASSWORD: eduplat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always

  celery:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - web
      - redis
    command: ["celery", "-A", "backend_project", "worker", "--loglevel=info"]
    volumes:
      - .:/backend_app

  celery-beat:
    build: .
    command: celery -A backend_project beat --loglevel=info
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
