# Generated by Django 5.1.6 on 2025-02-10 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseDescription', models.TextField()),
                ('IsApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('TagID', models.AutoField(primary_key=True, serialize=False)),
                ('TagName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('TopicID', models.AutoField(primary_key=True, serialize=False)),
                ('TopicName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=320, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('IsTeacher', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('LessonID', models.AutoField(primary_key=True, serialize=False)),
                ('LessonName', models.CharField(max_length=100)),
                ('LessonDescription', models.TextField()),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('PageID', models.AutoField(primary_key=True, serialize=False)),
                ('PageName', models.CharField(max_length=100)),
                ('PageDescription', models.TextField()),
                ('LessonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.lessons')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='TopicID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.topics'),
        ),
        migrations.CreateModel(
            name='Uploaded',
            fields=[
                ('FileID', models.AutoField(primary_key=True, serialize=False)),
                ('VideoURL', models.CharField(blank=True, max_length=100, null=True)),
                ('FileBlob', models.BinaryField(blank=True, null=True)),
                ('PageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pages')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.userinfo'),
        ),
        migrations.CreateModel(
            name='AppliedTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.courses')),
                ('TagID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend_app.tags')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('CourseID', 'TagID'), name='UniqueApplyTag')],
            },
        ),
        migrations.AddConstraint(
            model_name='courses',
            constraint=models.UniqueConstraint(fields=('UserID', 'CourseName'), name='UniqueCourseNamePerUser'),
        ),
    ]
