# Generated by Django 5.1.6 on 2025-03-01 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructorID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topicID', models.AutoField(primary_key=True, serialize=False)),
                ('topicName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=320, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=100)),
                ('courseDescription', models.TextField()),
                ('isPublished', models.BooleanField(default=False)),
                ('instructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('lessonID', models.AutoField(primary_key=True, serialize=False)),
                ('lessonName', models.CharField(max_length=100)),
                ('lessonDescription', models.TextField()),
                ('courseID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Uploaded',
            fields=[
                ('fileID', models.AutoField(primary_key=True, serialize=False)),
                ('videoURL', models.CharField(blank=True, max_length=100, null=True)),
                ('fileBlob', models.BinaryField(blank=True, null=True)),
                ('lessonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.lessons')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.userinfo'),
        ),
        migrations.CreateModel(
            name='LessonTag',
            fields=[
                ('lessonTagID', models.AutoField(primary_key=True, serialize=False)),
                ('lessonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.lessons')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.tags')),
            ],
            options={
                'unique_together': {('lessonID', 'tagID')},
            },
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('courseTagID', models.AutoField(primary_key=True, serialize=False)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.courses')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.tags')),
            ],
            options={
                'unique_together': {('courseID', 'tagID')},
            },
        ),
        migrations.CreateModel(
            name='TopicTag',
            fields=[
                ('topicTagID', models.AutoField(primary_key=True, serialize=False)),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.tags')),
                ('topicID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.topics')),
            ],
            options={
                'unique_together': {('topicID', 'tagID')},
            },
        ),
    ]
