# Generated by Django 5.1.6 on 2025-03-01 20:55

from django.db import migrations

def populate_initial_data(apps, schema_editor):
    UserInfo = apps.get_model('backend_app', 'UserInfo')
    Instructor = apps.get_model('backend_app', 'Instructor')
    Courses = apps.get_model('backend_app', 'Courses')
    Lessons = apps.get_model('backend_app', 'Lessons')
    Uploaded = apps.get_model('backend_app', 'Uploaded')
    Topics = apps.get_model('backend_app', 'Topics')
    Tags = apps.get_model('backend_app', 'Tags')
    LessonTag = apps.get_model('backend_app', 'LessonTag')
    CourseTag = apps.get_model('backend_app', 'CourseTag')
    TopicTag = apps.get_model('backend_app', 'TopicTag')

    # Create Users
    user1 = UserInfo.objects.create(username="admin", email="admin@example.com", password="adminpass")
    user2 = UserInfo.objects.create(username="teacher1", email="teacher1@example.com", password="teachpass")
    user3 = UserInfo.objects.create(username="teacher2", email="teacher2@example.com", password="teachpass")

    # Create Instructors
    instructor1 = Instructor.objects.create(userID=user1)
    instructor2 = Instructor.objects.create(userID=user2)
    instructor3 = Instructor.objects.create(userID=user3)

    # Create Topics
    topic_cs = Topics.objects.create(topicName="Computer Science")
    topic_math = Topics.objects.create(topicName="Mathematics")
    topic_ai = Topics.objects.create(topicName="Artificial Intelligence")

    # Create Courses
    course1 = Courses.objects.create(courseName="Intro to Python", courseDescription="Learn Python basics", isPublished=True, instructorID=instructor1)
    course2 = Courses.objects.create(courseName="Advanced Python", courseDescription="Deep dive into Python", isPublished=True, instructorID=instructor1)
    course3 = Courses.objects.create(courseName="Machine Learning", courseDescription="Intro to ML", isPublished=True, instructorID=instructor2)
    course4 = Courses.objects.create(courseName="Data Structures", courseDescription="Understanding algorithms and data structures", isPublished=True, instructorID=instructor3)
    course5 = Courses.objects.create(courseName="Linear Algebra", courseDescription="Essential math for CS", isPublished=True, instructorID=instructor3)

    # Create Lessons for each course
    lesson1 = Lessons.objects.create(courseID=course1, lessonName="Lesson 1: Variables", lessonDescription="Introduction to variables and data types")
    lesson2 = Lessons.objects.create(courseID=course1, lessonName="Lesson 2: Loops", lessonDescription="Understanding loops in Python")
    lesson3 = Lessons.objects.create(courseID=course2, lessonName="Lesson 1: OOP", lessonDescription="Object-oriented programming concepts in Python")
    lesson4 = Lessons.objects.create(courseID=course3, lessonName="Lesson 1: Linear Regression", lessonDescription="Basics of regression models")
    lesson5 = Lessons.objects.create(courseID=course4, lessonName="Lesson 1: Sorting Algorithms", lessonDescription="Understanding sorting techniques")
    lesson6 = Lessons.objects.create(courseID=course5, lessonName="Lesson 1: Matrices", lessonDescription="Matrix operations and applications")

    # Upload Videos
    Uploaded.objects.create(lessonID=lesson1, videoURL="https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    Uploaded.objects.create(lessonID=lesson2, videoURL="https://www.youtube.com/watch?v=R_FQU4KzN7A")
    Uploaded.objects.create(lessonID=lesson3, videoURL="https://www.youtube.com/watch?v=abc123")
    Uploaded.objects.create(lessonID=lesson4, videoURL="https://www.youtube.com/watch?v=xyz789")
    Uploaded.objects.create(lessonID=lesson5, videoURL="https://www.youtube.com/watch?v=math456")
    Uploaded.objects.create(lessonID=lesson6, videoURL="https://www.youtube.com/watch?v=ai987")

    # Create Tags
    tag_python = Tags.objects.create(tagName="Python")
    tag_ml = Tags.objects.create(tagName="Machine Learning")
    tag_algorithms = Tags.objects.create(tagName="Algorithms")
    tag_math = Tags.objects.create(tagName="Mathematics")
    tag_ds = Tags.objects.create(tagName="Data Science")

    # Assign Tags to Lessons & Courses
    LessonTag.objects.create(lessonID=lesson1, tagID=tag_python)
    LessonTag.objects.create(lessonID=lesson3, tagID=tag_python)
    LessonTag.objects.create(lessonID=lesson4, tagID=tag_ml)
    LessonTag.objects.create(lessonID=lesson5, tagID=tag_algorithms)
    LessonTag.objects.create(lessonID=lesson6, tagID=tag_math)

    CourseTag.objects.create(courseID=course1, tagID=tag_python)
    CourseTag.objects.create(courseID=course2, tagID=tag_python)
    CourseTag.objects.create(courseID=course3, tagID=tag_ml)
    CourseTag.objects.create(courseID=course4, tagID=tag_algorithms)
    CourseTag.objects.create(courseID=course5, tagID=tag_math)

    # Assign Topics to Courses
    TopicTag.objects.create(topicID=topic_cs, tagID=tag_python)
    TopicTag.objects.create(topicID=topic_ai, tagID=tag_ml)
    TopicTag.objects.create(topicID=topic_math, tagID=tag_math)

class Migration(migrations.Migration):
    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_data),
    ]

